/*
   Copyright (c) 2016 Piotr Czerczak
   All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __TFTLCD_ILI9325_H_
#define __TFTLCD_ILI9325_H_

#include <Adafruit_GFX.h>
#include <stdint.h>

#include "TTFLCD_ILI9325_registers.h"
#include "TTFLCD_shield_definition.h"


class TFTLCD_ILI9325 : public Adafruit_GFX {
  public:
  	TFTLCD_ILI9325();    // Constructor
  
	void 		drawPixel(int16_t x, int16_t y, uint16_t color);
	uint16_t	ReadRegisters16(uint8_t r);
	
  
  private:
	void 		init();

};		//End TFTLCD_ILI9325 class declaration


#endif    // __TFTLCD_ILI9325_H_
