/* 
  Copyright (c) 2016 Piotr Czerczak
  All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

#include "TTFLCD_ILI9325.h"

#include <stdint.h>

TFTLCD_ILI9325::TFTLCD_ILI9325() :
	Adafruit_GFX(TFTWIDTH, TFTHEIGHT) {
	
	
}

uint16_t TFTLCD_ILI9325::ReadRegisters16(uint8_t r) {
	uint16_t result;
	uint8_t hi, lo;

	nCS_LOW;
	RS_COMMAND;
	LCD_WRITE_8_bit(0x00);
	LCD_WRITE_8_bit(r);
	
	setReadDirInline();
	LCD_READ_8_bit(hi);
	LCD_READ_8_bit(lo);
	
	setWriteDirInline();
	nCS_HIGH;
	
	result = hi; result <<= 8; result |= lo;
	return result;
}


void TFTLCD_ILI9325::drawPixel(int16_t x, int16_t y, uint16_t color) {

	
}



